export type IconProps = {
  size?: number;
  className?: string;
  strokeWidth?: number;
  "aria-hidden"?: boolean | "true" | "false";
};

export { default as IconBell } from "./IconBell";
export { default as IconSearch } from "./IconSearch";
export { default as IconUser } from "./IconUser";
export { default as IconUsers } from "./IconUsers";
export { default as IconApps } from "./IconApps";
export { default as IconProducts } from "./IconProducts";
export { default as IconUssd } from "./IconUssd";
export { default as IconSms } from "./IconSms";
export { default as IconAuth } from "./IconAuth";
export { default as IconEcocash } from "./IconEcocash";
export { default as IconAirtime } from "./IconAirtime";
export { default as IconCustomer } from "./IconCustomer";
export { default as IconAnalytics } from "./IconAnalytics";
export { default as IconTicket } from "./IconTicket";
export { default as IconResource } from "./IconResource";
export { default as IconPlus } from "./IconPlus";
export { default as IconCheck } from "./IconCheck";
export { default as IconClose } from "./IconClose";
export { default as IconCopy } from "./IconCopy";
export { default as IconChevronDown } from "./IconChevronDown";
export { default as IconChevronRight } from "./IconChevronRight";
export { default as IconArrowRight } from "./IconArrowRight";
export { default as IconEye } from "./IconEye";
export { default as IconEyeOff } from "./IconEyeOff";
export { default as IconFilter } from "./IconFilter";
export { default as IconMenu } from "./IconMenu";
export { default as IconLogout } from "./IconLogout";
export { default as IconSettings } from "./IconSettings";
export { default as IconWarning } from "./IconWarning";
export { default as IconInfo } from "./IconInfo";
export { default as IconExternal } from "./IconExternal";
export { default as IconShield } from "./IconShield";
export { default as IconClock } from "./IconClock";
export { default as IconKey } from "./IconKey";
export { default as IconWebhook } from "./IconWebhook";
export { default as IconBilling } from "./IconBilling";
export { default as IconBook } from "./IconBook";
export { default as IconActivity } from "./IconActivity";
export { default as IconCloud } from "./IconCloud";
export { default as IconHelp } from "./IconHelp";
export { default as IconCommand } from "./IconCommand";
export { default as IconMoon } from "./IconMoon";
export { default as IconSun } from "./IconSun";
export { default as IconDocument } from "./IconDocument";
export { default as IconChat } from "./IconChat";
